-- NIX Nails: public customer reviews
-- Run this once in Supabase SQL Editor.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  rating integer not null check (rating between 1 and 5),
  review_text text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Anyone can read reviews that are displayed on the website.
drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews
for select
to anon, authenticated
using (true);

-- Customers can submit a review from the website.
drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
on public.reviews
for insert
to anon, authenticated
with check (
  char_length(trim(customer_name)) between 1 and 60
  and char_length(trim(review_text)) between 3 and 1000
  and rating between 1 and 5
);

grant select on public.reviews to anon, authenticated;
grant insert on public.reviews to anon, authenticated;

after table public.reviews enable row level security;
