-- NIX Nails booking system setup
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  instagram text,
  role text not null default 'customer' check (role in ('customer','owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  instagram text,
  email text not null,
  set_type text not null,
  shape text,
  length text,
  design_notes text,
  sizing_notes text,
  preferred_date date,
  extra_notes text,
  status text not null default 'pending' check (status in ('pending','confirmed','declined','completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.booking_photos (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_type text not null check (photo_type in ('inspiration','sizing')),
  storage_path text not null,
  original_name text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_photos enable row level security;

-- Profiles: customers can read/update their own profile; owners can read all profiles.
create policy "profiles own select" on public.profiles for select to authenticated using (id = auth.uid() or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));
create policy "profiles own insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles own update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Bookings: customers create/read their own; owners read/update all.
create policy "bookings customer insert" on public.bookings for insert to authenticated with check (user_id = auth.uid());
create policy "bookings customer read" on public.bookings for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));
create policy "bookings owner update" on public.bookings for update to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner')) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));

-- Photos: customers can add/read their own; owners can read all.
create policy "photos customer insert" on public.booking_photos for insert to authenticated with check (user_id = auth.uid());
create policy "photos customer read" on public.booking_photos for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));

-- Automatically create a profile when a customer signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, instagram)
  values (new.id, new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'instagram')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Storage bucket for booking images.
insert into storage.buckets (id, name, public)
values ('booking-photos', 'booking-photos', false)
on conflict (id) do nothing;

-- Storage: each customer stores files in a folder named with their auth user id.
create policy "booking photos upload own folder" on storage.objects for insert to authenticated with check (
  bucket_id = 'booking-photos' and (storage.foldername(name))[1] = auth.uid()::text
);
create policy "booking photos read own or owner" on storage.objects for select to authenticated using (
  bucket_id = 'booking-photos' and (
    (storage.foldername(name))[1] = auth.uid()::text
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner')
  )
);

-- IMPORTANT: after your first owner account is created, run this once with your owner email:
-- update public.profiles set role = 'owner' where id = (select id from auth.users where email = 'YOUR_EMAIL_HERE');
